### ISSUE TITLE
Add administrator POST authentication for /add-question endpoint

### ISSUE THREAD

**Issue by ActuallyConnor** [ActuallyConnor/Trivious#7]
I want to add a new POST endpoint called /add-question. This endpoint will require some type of Basic Authentication. The subsequent goal is to setup this endpoint so that when someone makes a POST request to this endpoint and provides the Basic Auth credentials, they are able to add a new question to the database.

Project is currently on Laravel 7. Here are the Laravel 7 Authentication docs [https://laravel.com/docs/7.x/authentication](https://laravel.com/docs/7.x/authentication)

**Comment by mgilberties** [comment]
Can I take this one please?

**Comment by mgilberties** [comment]
Note: Migrations for questions and categories tables missing so unable to fully test. Hit the new endpoint using Postman to test controller method validation and successfully got a response.
