### ISSUE TITLE
Add ability to add questions at POST /add-question endpoint 

### ISSUE THREAD

**Issue by ActuallyConnor** [ActuallyConnor/Trivious#8]
This issue is linked with [https://github.com/ActuallyConnor/Trivious/issues/7](https://github.com/ActuallyConnor/Trivious/issues/7)

As mentioned in that issue, I want to setup this endpoint so that when it is hit, a question can be added to the database.

Project is currently on Laravel 7. Here are the Laravel 7 docs for Routing [https://laravel.com/docs/7.x/routing](https://laravel.com/docs/7.x/routing). Here are the Laravel 7 docs for the Eloquent ORM [https://laravel.com/docs/7.x/eloquent](https://laravel.com/docs/7.x/eloquent_

**Comment by GueGuerreiro** [comment]
I guess this was added in #7 and we should close this issue as well?

**Comment by ActuallyConnor** [comment]
@GueGuerreiro was correct, closing issue
